sudo: required

services:
    - docker

script:
    - >
        docker build \
             -t 3ds-dev \
            --build-arg git_commit=$TRAVIS_COMMIT \
            --build-arg build_date=$(date --rfc-3339=seconds | sed 's/ /T/') \
            --build-arg version_number=${TRAVIS_TAG:-"git-$TRAVIS_COMMIT"} \
            .

after_success:
    - if [ "$TRAVIS_TAG" ]; then
        docker tag 3ds-dev "ahoischen/3ds-dev:$TRAVIS_TAG";
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push "ahoischen/3ds-dev:$TRAVIS_TAG";
      fi
